# Generated by Django 4.0.4 on 2022-11-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_field', models.IntegerField(db_column='Class', primary_key=True, serialize=False)),
                ('strength', models.IntegerField(db_column='Strength')),
                ('fees', models.IntegerField(db_column='Fees')),
                ('subject1', models.CharField(blank=True, db_column='Subject1', max_length=10, null=True)),
                ('maxmarksinsub1', models.IntegerField(blank=True, db_column='MaxMarksInSub1', null=True)),
                ('subject2', models.CharField(blank=True, db_column='Subject2', max_length=10, null=True)),
                ('maxmarksinsub2', models.IntegerField(blank=True, db_column='MaxMarksInSub2', null=True)),
                ('subject3', models.CharField(blank=True, db_column='Subject3', max_length=10, null=True)),
                ('maxmarksinsub3', models.IntegerField(blank=True, db_column='MaxMarksInSub3', null=True)),
                ('subject4', models.CharField(blank=True, db_column='Subject4', max_length=10, null=True)),
                ('maxmarksinsub4', models.IntegerField(blank=True, db_column='MaxMarksInSub4', null=True)),
                ('subject5', models.CharField(blank=True, db_column='Subject5', max_length=10, null=True)),
                ('maxmarksinsub5', models.IntegerField(blank=True, db_column='MaxMarksInSub5', null=True)),
                ('subject6', models.CharField(blank=True, db_column='Subject6', max_length=10, null=True)),
                ('maxmarksinsub6', models.IntegerField(blank=True, db_column='MaxMarksInSub6', null=True)),
                ('subject7', models.CharField(blank=True, db_column='Subject7', max_length=10, null=True)),
                ('maxmarksinsub7', models.IntegerField(blank=True, db_column='MaxMarksInSub7', null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('enrollno', models.AutoField(db_column='EnrollNo', primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=100, null=True)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
                ('class_field', models.IntegerField(db_column='Class')),
                ('dateofenrollment', models.DateTimeField(db_column='DateOfEnrollment')),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectcode', models.CharField(db_column='SubjectCode', max_length=10, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(db_column='SubjectName', max_length=45)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.IntegerField(db_column='TeacherID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('salary', models.BigIntegerField(blank=True, db_column='Salary', null=True)),
                ('dateofjoining', models.DateTimeField(db_column='DateOfJoining')),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('enrollno', models.OneToOneField(db_column='EnrollNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teacher.students')),
                ('class_field', models.IntegerField(db_column='Class')),
                ('april', models.IntegerField(blank=True, db_column='April', null=True)),
                ('may', models.IntegerField(blank=True, db_column='May', null=True)),
                ('june', models.IntegerField(blank=True, db_column='June', null=True)),
                ('july', models.IntegerField(blank=True, db_column='July', null=True)),
                ('august', models.IntegerField(blank=True, db_column='August', null=True)),
                ('september', models.IntegerField(blank=True, db_column='September', null=True)),
                ('october', models.IntegerField(blank=True, db_column='October', null=True)),
                ('november', models.IntegerField(blank=True, db_column='November', null=True)),
                ('december', models.IntegerField(blank=True, db_column='December', null=True)),
                ('january', models.IntegerField(blank=True, db_column='January', null=True)),
                ('february', models.IntegerField(blank=True, db_column='February', null=True)),
                ('march', models.IntegerField(blank=True, db_column='March', null=True)),
                ('totalworking_days', models.IntegerField(blank=True, db_column='TotalWorking_Days', null=True)),
                ('percentage', models.FloatField(blank=True, db_column='Percentage', null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('enrollno', models.OneToOneField(db_column='EnrollNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teacher.students')),
                ('class_field', models.IntegerField(db_column='Class')),
                ('marksinsub1', models.IntegerField(blank=True, db_column='MarksInSub1', null=True)),
                ('marksinsub2', models.IntegerField(blank=True, db_column='MarksInSub2', null=True)),
                ('marksinsub3', models.IntegerField(blank=True, db_column='MarksInSub3', null=True)),
                ('marksinsub4', models.IntegerField(blank=True, db_column='MarksInSub4', null=True)),
                ('marksinsub5', models.IntegerField(blank=True, db_column='MarksInSub5', null=True)),
                ('marksinsub6', models.IntegerField(blank=True, db_column='MarksInSub6', null=True)),
                ('marksinsub7', models.IntegerField(blank=True, db_column='MarksInSub7', null=True)),
                ('percentagescore', models.FloatField(blank=True, db_column='PercentageScore', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=50, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('teacherid', models.OneToOneField(db_column='TeacherID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='teacher.teachers')),
                ('aadhaarno', models.PositiveBigIntegerField(db_column='AadhaarNo', unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('contactno', models.BigIntegerField(blank=True, db_column='ContactNo', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('dob', models.DateField(db_column='DOB')),
                ('bloodgrp', models.CharField(blank=True, db_column='BloodGrp', max_length=3, null=True)),
                ('caste', models.CharField(blank=True, db_column='Caste', max_length=5, null=True)),
                ('religion', models.CharField(blank=True, db_column='Religion', max_length=10, null=True)),
            ],
            options={
                'db_table': 'teacher_details',
                'managed': False,
            },
        ),
    ]
