# Generated by Django 5.1.2 on 2024-10-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='enrollno',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.RemoveField(
            model_name='results',
            name='enrollno',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='teacherid',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='TeacherDetails',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
