# Generated by Django 4.0.4 on 2022-11-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('applicantid', models.AutoField(db_column='ApplicantID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
                ('classtobeenrolled', models.IntegerField(db_column='ClassToBeEnrolled')),
                ('lastschoolattended', models.CharField(db_column='LastSchoolAttended', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=1)),
                ('dob', models.DateField(db_column='DOB')),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('bloodgrp', models.CharField(db_column='BloodGrp', max_length=4)),
                ('aadhaarno', models.PositiveBigIntegerField(db_column='AadhaarNo', unique=True)),
                ('contactno', models.BigIntegerField(blank=True, db_column='ContactNo', null=True)),
                ('father_s_name', models.CharField(blank=True, db_column="Father's_Name", max_length=45, null=True)),
                ('father_s_occupation', models.CharField(blank=True, db_column="Father's_Occupation", max_length=45, null=True)),
                ('father_s_aadhaarno', models.PositiveBigIntegerField(blank=True, db_column="Father's_AadhaarNo", null=True)),
                ('father_s_email', models.CharField(blank=True, db_column="Father's_Email", max_length=45, null=True)),
                ('father_s_contactno', models.BigIntegerField(blank=True, db_column="Father's_ContactNo", null=True)),
                ('mother_s_name', models.CharField(blank=True, db_column="Mother's_Name", max_length=45, null=True)),
                ('mother_s_occupation', models.CharField(blank=True, db_column="Mother's_Occupation", max_length=45, null=True)),
                ('mother_s_aadhaarno', models.PositiveBigIntegerField(blank=True, db_column="Mother's_AadhaarNo", null=True)),
                ('mother_s_email', models.CharField(blank=True, db_column="Mother's_Email", max_length=45, null=True)),
                ('mother_s_contactno', models.BigIntegerField(blank=True, db_column="Mother's_ContactNo", null=True)),
                ('guardian_s_name', models.CharField(blank=True, db_column="Guardian's_Name", max_length=45, null=True)),
                ('guardian_s_occupation', models.CharField(blank=True, db_column="Guardian's_Occupation", max_length=45, null=True)),
                ('guardian_s_aadhaarno', models.PositiveBigIntegerField(blank=True, db_column="Guardian's_AadhaarNo", null=True)),
                ('guardian_s_email', models.CharField(blank=True, db_column="Guardian's_Email", max_length=45, null=True)),
                ('guardian_s_contactno', models.BigIntegerField(blank=True, db_column="Guardian's_ContactNo", null=True)),
                ('familyincome', models.CharField(db_column='FamilyIncome', max_length=10)),
                ('caste', models.CharField(db_column='Caste', max_length=5)),
                ('religion', models.CharField(db_column='Religion', max_length=45)),
            ],
            options={
                'db_table': 'applicants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('applicantid', models.OneToOneField(db_column='ApplicantID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MainApp.applicants')),
                ('testscore', models.IntegerField(blank=True, db_column='TestScore', null=True)),
                ('classtobeenrolled', models.IntegerField(db_column='ClassToBeEnrolled')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'application_status',
                'managed': False,
            },
        ),
    ]
