# Generated by Django 5.1.2 on 2024-10-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_user_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('enrollno', models.AutoField(db_column='EnrollNo', primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=100, null=True)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
                ('class_field', models.IntegerField(db_column='Class')),
                ('dateofenrollment', models.DateTimeField(db_column='DateOfEnrollment')),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_field', models.IntegerField(db_column='Class', primary_key=True, serialize=False)),
                ('strength', models.IntegerField(db_column='Strength')),
                ('fees', models.IntegerField(db_column='Fees')),
                ('subject1', models.CharField(blank=True, db_column='Subject1', max_length=10, null=True)),
                ('maxmarksinsub1', models.IntegerField(blank=True, db_column='MaxMarksInSub1', null=True)),
                ('subject2', models.CharField(blank=True, db_column='Subject2', max_length=10, null=True)),
                ('maxmarksinsub2', models.IntegerField(blank=True, db_column='MaxMarksInSub2', null=True)),
                ('subject3', models.CharField(blank=True, db_column='Subject3', max_length=10, null=True)),
                ('maxmarksinsub3', models.IntegerField(blank=True, db_column='MaxMarksInSub3', null=True)),
                ('subject4', models.CharField(blank=True, db_column='Subject4', max_length=10, null=True)),
                ('maxmarksinsub4', models.IntegerField(blank=True, db_column='MaxMarksInSub4', null=True)),
                ('subject5', models.CharField(blank=True, db_column='Subject5', max_length=10, null=True)),
                ('maxmarksinsub5', models.IntegerField(blank=True, db_column='MaxMarksInSub5', null=True)),
                ('subject6', models.CharField(blank=True, db_column='Subject6', max_length=10, null=True)),
                ('maxmarksinsub6', models.IntegerField(blank=True, db_column='MaxMarksInSub6', null=True)),
                ('subject7', models.CharField(blank=True, db_column='Subject7', max_length=10, null=True)),
                ('maxmarksinsub7', models.IntegerField(blank=True, db_column='MaxMarksInSub7', null=True)),
            ],
            options={
                'db_table': 'classes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('relationship', models.CharField(db_column='Relationship', max_length=45)),
                ('contactno', models.BigIntegerField(blank=True, db_column='ContactNo', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('occupation', models.CharField(blank=True, db_column='Occupation', max_length=45, null=True)),
                ('aadhaarno', models.PositiveBigIntegerField(db_column='AadhaarNo')),
            ],
            options={
                'db_table': 'guardian_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainappUserProfiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mainapp_user_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subjectcode', models.CharField(db_column='SubjectCode', max_length=10, primary_key=True, serialize=False)),
                ('subjectname', models.CharField(db_column='SubjectName', max_length=45)),
            ],
            options={
                'db_table': 'subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.IntegerField(db_column='TeacherID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=45)),
                ('lastname', models.CharField(db_column='LastName', max_length=45)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('salary', models.BigIntegerField(blank=True, db_column='Salary', null=True)),
                ('dateofjoining', models.DateTimeField(db_column='DateOfJoining')),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('enrollno', models.OneToOneField(db_column='EnrollNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MainApp.students')),
                ('class_field', models.IntegerField(db_column='Class')),
                ('april', models.IntegerField(blank=True, db_column='April', null=True)),
                ('may', models.IntegerField(blank=True, db_column='May', null=True)),
                ('june', models.IntegerField(blank=True, db_column='June', null=True)),
                ('july', models.IntegerField(blank=True, db_column='July', null=True)),
                ('august', models.IntegerField(blank=True, db_column='August', null=True)),
                ('september', models.IntegerField(blank=True, db_column='September', null=True)),
                ('october', models.IntegerField(blank=True, db_column='October', null=True)),
                ('november', models.IntegerField(blank=True, db_column='November', null=True)),
                ('december', models.IntegerField(blank=True, db_column='December', null=True)),
                ('january', models.IntegerField(blank=True, db_column='January', null=True)),
                ('february', models.IntegerField(blank=True, db_column='February', null=True)),
                ('march', models.IntegerField(blank=True, db_column='March', null=True)),
                ('totalworking_days', models.IntegerField(blank=True, db_column='TotalWorking_Days', null=True)),
                ('percentage', models.FloatField(blank=True, db_column='Percentage', null=True)),
            ],
            options={
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('enrollno', models.OneToOneField(db_column='EnrollNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MainApp.students')),
                ('class_field', models.IntegerField(db_column='Class')),
                ('marksinsub1', models.IntegerField(blank=True, db_column='MarksInSub1', null=True)),
                ('marksinsub2', models.IntegerField(blank=True, db_column='MarksInSub2', null=True)),
                ('marksinsub3', models.IntegerField(blank=True, db_column='MarksInSub3', null=True)),
                ('marksinsub4', models.IntegerField(blank=True, db_column='MarksInSub4', null=True)),
                ('marksinsub5', models.IntegerField(blank=True, db_column='MarksInSub5', null=True)),
                ('marksinsub6', models.IntegerField(blank=True, db_column='MarksInSub6', null=True)),
                ('marksinsub7', models.IntegerField(blank=True, db_column='MarksInSub7', null=True)),
                ('percentagescore', models.FloatField(blank=True, db_column='PercentageScore', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=50, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('enrollno', models.OneToOneField(db_column='EnrollNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MainApp.students')),
                ('aadhaarno', models.PositiveBigIntegerField(db_column='AadhaarNo', unique=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('contactno', models.BigIntegerField(blank=True, db_column='ContactNo', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('dob', models.DateField(db_column='DOB')),
                ('bloodgrp', models.CharField(blank=True, db_column='BloodGrp', max_length=3, null=True)),
                ('caste', models.CharField(blank=True, db_column='Caste', max_length=5, null=True)),
                ('religion', models.CharField(blank=True, db_column='Religion', max_length=10, null=True)),
                ('familyincome', models.CharField(db_column='FamilyIncome', max_length=10)),
            ],
            options={
                'db_table': 'student_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('teacherid', models.OneToOneField(db_column='TeacherID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MainApp.teachers')),
                ('aadhaarno', models.PositiveBigIntegerField(db_column='AadhaarNo', unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=45, null=True)),
                ('contactno', models.BigIntegerField(blank=True, db_column='ContactNo', null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('dob', models.DateField(db_column='DOB')),
                ('bloodgrp', models.CharField(blank=True, db_column='BloodGrp', max_length=3, null=True)),
                ('caste', models.CharField(blank=True, db_column='Caste', max_length=5, null=True)),
                ('religion', models.CharField(blank=True, db_column='Religion', max_length=10, null=True)),
            ],
            options={
                'db_table': 'teacher_details',
                'managed': False,
            },
        ),
    ]
